theme: jekyll-theme-cayman
title: FunTuna Fork
description: a combination of PS2 Software prepared to ease the pain of getting a stable exploit on a ps2 uncompatible with FreeMcBoot
show_downloads: true

github:
      index: https://israpps.github.io/Funtuna-Fork/index.html
      zip_url: https://github.com/israpps/Funtuna-Fork/releases
      common_questions: https://israpps.github.io/Funtuna-Fork/ASK.html
      tuto_url: https://israpps.github.io/Funtuna-Fork/INSTALL.html
      
