blank_issues_enabled: true
contact_links:


- name: Bug report rules 
  url: https://github.com/israpps/Funtuna-Fork/wiki/issue-rules
  about: read this before creating issues

- name: Reglas para reportar bugs
  url: https://github.com/israpps/Funtuna-Fork/wiki/repotar-issues
  about: lee esto antes de reportar bugs
