name: Release Funtuna
on:
  workflow_dispatch:
  push:
    paths:
      - '__Release/**'
      - '.github/workflows/*.yml'

  #schedule:
  # - cron: "0 15 * * *"
jobs:
  check-binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: "Check file existence"
        uses: andstor/file-existence-action@v1
        with:
          files: "__Binaries/BOOT.ELF, __Binaries/CFG.ELF , __Binaries/USBD.IRX , __Binaries/USBHDFSD.IRX , __Binaries/ULE.ELF , __Binaries/LAUNCHELF.CNF , __Binaries/POWEROFF.ELF"
          allow_failure: "true"



  Repakc&Release:
    runs-on: ubuntu-latest
    needs: check-binaries
    steps:
    
    - uses: actions/checkout@v1
    - name: Zip Folder
      run: |
        cd __Release
        SCH=${GITHUB_SHA::7}
        echo commit $SCH >>commit.txt
        TARGET=FunTuna\[$SCH\].zip
        echo TARGET is $TARGET
        zip -r $TARGET *
        ls
    
    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: FunTuna
        path: __Release/*\[*\].zip
 
    - name: Create release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Latest automated Repack"
        files: |
                __Release/*\[*\].zip
