name: Release Funtuna
on:
  workflow_dispatch:
  push:
    paths:
      - '__Release/**'
      - '.github/workflows/*.yml'

  #schedule:
  # - cron: "0 15 * * *"
jobs:
  check-binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: "Check file existence"
        uses: andstor/file-existence-action@v1
        with:
          files: "__Binaries/BOOT.ELF, __Binaries/CFG.ELF , __Binaries/USBD.IRX , __Binaries/USBHDFSD.IRX , __Binaries/ULE.ELF , __Binaries/LAUNCHELF.CNF , __Binaries/POWEROFF.ELF"
          allow_failure: "true"



  Repack_and_Release:
    runs-on: ubuntu-latest
    needs: check-binaries
    steps:
    

    - name: checkout code for release
      uses: actions/checkout@v1

    - name: Place binaries at Specific locations
      run: |
        cd __Binaries/
        
        cp BOOT.ELF "../__Release/!Funtuna-Basic/BOOT/BOOT.ELF"
        cp BOOT.ELF "../__Release/!Funtuna-Clean/BOOT/BOOT.ELF"
        cp BOOT.ELF "../__Release/!Funtuna-Basic - Light/BOOT/BOOT.ELF"

        cp CFG.ELF "../__Release/!Funtuna-Basic/BOOT/CFG.ELF"
        cp CFG.ELF "../__Release/!Funtuna-Clean/BOOT/CFG.ELF"
        cp CFG.ELF "../__Release/!Funtuna-Basic - Light/BOOT/CFG.ELF"

        cp LAUNCHELF.CNF "../__Release/!Funtuna-Basic/BOOT/LAUNCHELF.CNF"
        cp LAUNCHELF.CNF "../__Release/!Funtuna-Clean/BOOT/LAUNCHELF.CNF"
        cp LAUNCHELF.CNF "../__Release/!Funtuna-Basic - Light/BOOT/LAUNCHELF.CNF"

        cp POWEROFF.ELF "../__Release/!Funtuna-Basic/BOOT/POWEROFF.ELF"
        cp POWEROFF.ELF "../__Release/!Funtuna-Clean/BOOT/POWEROFF.ELF"
        cp POWEROFF.ELF "../__Release/!Funtuna-Basic - Light/BOOT/POWEROFF.ELF"

        cp USBD.IRX "../__Release/!Funtuna-Basic/BOOT/USBD.IRX"
        cp USBD.IRX "../__Release/!Funtuna-Clean/BOOT/USBD.IRX"
        cp USBD.IRX "../__Release/!Funtuna-Basic - Light/BOOT/USBD.IRX"

        cp USBHDFSD.IRX "../__Release/!Funtuna-Basic/BOOT/USBHDFSD.IRX"
        cp USBHDFSD.IRX "../__Release/!Funtuna-Clean/BOOT/USBHDFSD.IRX"
        cp USBHDFSD.IRX "../__Release/!Funtuna-Basic - Light/BOOT/USBHDFSD.IRX"

        cp ULE.ELF "../__Release/!Funtuna-Basic/BOOT/ULE.ELF"
        cp ULE.ELF "../__Release/!Funtuna-Clean/BOOT/ULE.ELF"
        cp ULE.ELF "../__Release/!Funtuna-Basic - Light/BOOT/ULE.ELF"
        
        cd ..

    
    - name: Zip Folder
      run: |
        cd __Release
        SCH=${GITHUB_SHA::7}
        echo commit $SCH >>commit.txt
        TARGET=FunTuna\[$SCH\].zip
        echo TARGET is $TARGET
        zip -r $TARGET *
        ls -R 
    
    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: FunTuna
        path: |
             __Release/*.zip
 
    - name: Create release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Latest automated Repack"
        files: |
                __Release/*.zip


  generate-manifest:
    runs-on: ubuntu-latest
    needs: check-binaries
    steps:
    
      - name: checkout package
        uses: actions/checkout@v1

      - name: generate manifest
        run: |  
          ls -R __Release





