name: Create Release
on: 
workflow_dispatch:
push:

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'funtuna-release.zip'
          path: ./__Dependencies/BOOT/
