name: Release Funtuna
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - __Release/**
      - .github/workflows/*.yml
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v1
    - name: Zip Folder
      run: |
        cd __Release
        #zip -f format('FunTuna[${0}].zip, ${GITHUB_SHA::7}') *
        SCH=${GITHUB_SHA::7}
        zip -r "FunTuna[$SCH].zip" *
    
    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: FunTuna
        path: __Release/*.zip
 
    - name: Create release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Latest automated Repack"
        files: |
                __Release/*.zip
