name: FunTuna-Release
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'FunTuna.ZIP'
        path: /__Dependencies/BOOT/
        
        
    - name: Upload Release
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "FunTuna.ZIP"
        token: ${{ secrets.GITHUB_TOKEN }}
