name: Release Funtuna
on:
  workflow_dispatch:
  push:
    paths:
      - '__Release/**'
      - '.github/workflows/*.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v1
    - name: Zip Folder
      run: |
        cd __Release
        SCH=${GITHUB_SHA::7}
        echo commit $SCH >>commit.txt
        TARGET=FunTuna\[$SCH\].zip
        echo TARGET is $TARGET
        zip -r $TARGET *
        ls
    
    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: FunTuna
        path: __Release/*\[*\].zip
 
    - name: Create release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Latest automated Repack"
        files: |
                __Release/*\[*\].zip
