name: Update uLaunchELF

on:
  push:
  repository_dispatch:
    types: [Component_update]

jobs:
  rewrite-jsom:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Update wLaunchELF_ISR
      run: |
         wget https://github.com/israpps/wLaunchELF_ISR/releases/download/latest/BOOT.ELF -O __Binaries/ULE.ELF
         wget https://github.com/israpps/wLaunchELF_ISR/releases/download/latest/BOOT.ELF -O __Release/ULE_psu.ELF

    - uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        message: 'Update uLaunchELF 4.43x_isr'
